WIP add Unsafe to static initializer
Currently throws
java.lang.UnsatisfiedLinkError: sun.misc.Unsafe.registerNatives()V

Probably because both system class loader and javassist loaded the
Unsafe class.